DROP TABLE IF EXISTS cars;

CREATE TABLE cars (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  type TEXT NOT NULL,
  year INTEGER NOT NULL,
  price_clp INTEGER NOT NULL,
  region TEXT NOT NULL,
  img TEXT NOT NULL
);
